name: Build APK
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip
          unzip -o proxygeotoolkit.zip -d .
          ls -la

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build release APK
        working-directory: ProxyGeoToolkit
        run: |
          gradle assembleRelease --no-daemon
          ls -R app/build/outputs/apk/release || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ProxyGeoToolkit/app/build/outputs/apk/release/*.apk
